### ISSUE TITLE
Checkboxes for impaired rolls

### ISSUE THREAD

**Issue by malkilthewizard** [maqloner/mythic-bastionland#2]
When rolling to attack there is an individual checkbox for impairment for every weapon. Wouldn't it be easier to have a single checkbox since impairment is added to every attack roll?

**Comment by maqloner** [comment]
Based on a discussion with Chris, individual weapons and shields can be impaired with a Gambit.

**Comment by malkilthewizard** [comment]
Oh, alright! Well then it makes sense. Thanks for the reply!
