### ISSUE TITLE
Manually adjust armor values for creatures

### ISSUE THREAD

**Issue by malkilthewizard** [maqloner/mythic-bastionland#3]
I noticed that the armor value on creature sheets always displays "0", even when adding armour items to them. Would be nice if you could manually change the armor values instead of having to add the armor when rolling for damage taken. Maybe there is a reason for the way it is now, but it's just a suggestion.

**Comment by maqloner** [comment]
I've tested it and it's working as intended. Armors need to be added to a creature or any actors and the equipped button needs to be clicked. The Armour value is a calculated value based on all equipped items with an armor value.

**Comment by malkilthewizard** [comment]
Alright. I must've forgotten to equip the armour then. However, it feels a bit weird to add physical armour to things that are not humanoids. I'm not a Foundry expert, but it should be possible to create an armour asset i.e. "thick hide" and add it to a beast or something?

**Comment by maqloner** [comment]
Yes, creature in MB have armor like "Thick hide A1". You can create and assign items to actors using the "add item" button on their sheet, or with the "create item" button in the items tab of foundry sidebar if you want to reused them.
